name: Build SDL Native

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - 'CMakeLists.txt'

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure win-x64
      run: cmake S . -B build_win_64 -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build win-x64
      run: cmake --build build_win_64 --config Release

    - name: Configure win-arm64
      run: cmake S . -B build_win_arm64 -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Release
    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Release\SDL3.dll bin/win-x64/native
        mv build_win_arm64\bin\Release\SDL3.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v3
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential git \
            pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libusb-1.0-0-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
    - name: Configure linux-x64
      run: cmake S . -B build_linux_64 -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: Build linux-x64
      run: cmake --build build_linux_64 --config Release --verbose --parallel

    # Linux artifact 
    - name: package_linux
      run: |
        mkdir -p bin/linux-x64/native
        mv build_linux_64/lib/libSDL3.so.0.0.0 bin/linux-x64/native/libSDL3-0.0.so.0
    - uses: actions/upload-artifact@v3
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      run: |
        brew install \
          ninja \
          llvm

    - name: Configure osx-universal
      run: cmake -S . -B build_osx -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: Build osx-universal
      run: cmake --build build_osx --config Release --verbose --parallel

    # macOS artifacts
    - name: package_osx
      run: |
        mkdir -p bin/osx-universal/native
        mv build_osx/lib/libSDL3.1.0.0.dylib bin/osx-universal/native/libSDL3.dylib
    - uses: actions/upload-artifact@v3
      with:
        name: libs_osx
        path: bin

  combine:
    name: combine artifacts
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download windows lib
        uses: actions/download-artifact@v3
        with:
          name: libs_windows
          path: Alimer.Bindings.SDL/runtimes
      - name: Download ubuntu lib
        uses: actions/download-artifact@v3
        with:
          name: libs_linux
          path: Alimer.Bindings.SDL/runtimes
      - name: Download macos lib
        uses: actions/download-artifact@v3
        with:
          name: libs_osx
          path: Alimer.Bindings.SDL/runtimes
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Alimer.Bindings.SDL/runtimes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.3
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com