
name: Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '*.md'
      - 'LICENSE'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure Win64
      run: cmake . -G "Visual Studio 17 2022" -A x64 -Bbuild_win_64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build Win64
      run: cmake --build build_win_64 --config Release

    - name: Configure Win64 ARM64
      run: cmake . -G "Visual Studio 17 2022" -A ARM64 -Bbuild_win_arm64 -DCMAKE_BUILD_TYPE:String=Release
    - name: Build Win64
      run: cmake --build build_win_arm64 --config Release
    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Release\SDL2.dll bin/win-x64/native
        mv build_win_arm64\bin\Release\SDL2.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v3
      with:
        name: libs_windows
        path: bin
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: [ windows ]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          path: Alimer.Bindings.SDL/runtimes

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: Alimer.Bindings.SDL/runtimes

      - name: Pack
        run: dotnet pack Alimer.Bindings.SDL/Alimer.Bindings.SDL.csproj --configuration Release

      - uses: actions/upload-artifact@v3
        with:
          name: nuget_release
          path: |
            ./artifacts/*
          if-no-files-found: error
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: |
            libs_windows
